version: "3.3"
services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "3000:3000"
    volumes:
      - react:/code
    
    depends_on:
      - web
  web:
    restart: always
    build: .
    volumes:
      - react:/code
    tty: true


volumes:
  react: